---
- name: Install python3 and docker
  hosts: ec2-docker
  become: yes
  gather_facts: False
  tasks:
    - name: Make sure python3 and docker are installed
      vars:
        ansible_python_interpreter: /usr/bin/python
      yum:
        name: 
          - python3
          - docker
        update_cache: yes
        state: present
    
- name: Install docker compose
  hosts: ec2-docker
  become: yes
  tasks:
    - name: Install Docker compose
      get_url: 
        url: https://github.com/docker/compose/releases/download/1.27.4/docker-compose-Linux-{{lookup('pipe', 'uname -m')}}
        dest: /usr/local/bin/docker-compose
        mode: +x 

- name: Start docker
  hosts: ec2-docker
  become: yes
  tasks:
    - name: Ensure docker is running
      systemd:
        name: docker
        state: started 
    - name: Install docker python module
      pip:
        name: 
          - docker
          - docker-compose

- name: Add ec2-user to docker group
  hosts: ec2-docker
  become: yes
  tasks:
    - name: Add ec2-user to docker group
      user:
        name: ec2-user
        groups: docker
        append: yes
    - name: Reconnect to server session
      meta: reset_connection

- name: Start docker containers
  hosts: ec2-docker
  become: yes
  vars_prompt:
    - name: docker_password
      prompt: Enter password for docker registry
  tasks:
    - name: Copy docker compose
      copy:
        src: /Users/andres/Documents/DevOpsBootcamp_TechWorld/proyectos/Ansible_proyectos/ansible_docker/docker-compose.yaml
        dest: /home/ec2-user/docker-compose.yaml
    - name: Docker login
      docker_login: 
        registry_url: https://index.docker.io/v1/
        username: f90mora
        password: "{{docker_password}}"
    - name: Start container from compose
      docker_compose:
        project_src: /home/ec2-user
        

  